ZEROSHOT_TEMPLATES = {
    'imagenet': [
        'a bad photo of a {}.',
        'a photo of many {}.',
        'a sculpture of a {}.',
        'a photo of the hard to see {}.',
        'a low resolution photo of the {}.',
        'a rendering of a {}.',
        'graffiti of a {}.',
        'a bad photo of the {}.',
        'a cropped photo of the {}.',
        'a tattoo of a {}.',
        'the embroidered {}.',
        'a photo of a hard to see {}.',
        'a bright photo of a {}.',
        'a photo of a clean {}.',
        'a photo of a dirty {}.',
        'a dark photo of the {}.',
        'a drawing of a {}.',
        'a photo of my {}.',
        'the plastic {}.',
        'a photo of the cool {}.',
        'a close-up photo of a {}.',
        'a black and white photo of the {}.',
        'a painting of the {}.',
        'a painting of a {}.',
        'a pixelated photo of the {}.',
        'a sculpture of the {}.',
        'a bright photo of the {}.',
        'a cropped photo of a {}.',
        'a plastic {}.',
        'a photo of the dirty {}.',
        'a jpeg corrupted photo of a {}.',
        'a blurry photo of the {}.',
        'a photo of the {}.',
        'a good photo of the {}.',
        'a rendering of the {}.',
        'a {} in a video game.',
        'a photo of one {}.',
        'a doodle of a {}.',
        'a close-up photo of the {}.',
        'a photo of a {}.',
        'the origami {}.',
        'the {} in a video game.',
        'a sketch of a {}.',
        'a doodle of the {}.',
        'a origami {}.',
        'a low resolution photo of a {}.',
        'the toy {}.',
        'a rendition of the {}.',
        'a photo of the clean {}.',
        'a photo of a large {}.',
        'a rendition of a {}.',
        'a photo of a nice {}.',
        'a photo of a weird {}.',
        'a blurry photo of a {}.',
        'a cartoon {}.',
        'art of a {}.',
        'a sketch of the {}.',
        'a embroidered {}.',
        'a pixelated photo of a {}.',
        'itap of the {}.',
        'a jpeg corrupted photo of the {}.',
        'a good photo of a {}.',
        'a plushie {}.',
        'a photo of the nice {}.',
        'a photo of the small {}.',
        'a photo of the weird {}.',
        'the cartoon {}.',
        'art of the {}.',
        'a drawing of the {}.',
        'a photo of the large {}.',
        'a black and white photo of a {}.',
        'the plushie {}.',
        'a dark photo of a {}.',
        'itap of a {}.',
        'graffiti of the {}.',
        'a toy {}.',
        'itap of my {}.',
        'a photo of a cool {}.',
        'a photo of a small {}.',
        'a tattoo of the {}.',
    ],
    # https://github.com/google-research/big_vision/blob/main/big_vision/evaluators/proj/image_text/prompt_engineering_constants.py.
    'imagenet_best': [
        'itap of a {}.',
        'a bad photo of the {}.',
        'a origami {}.',
        'a photo of the large {}.',
        'a {} in a video game.',
        'art of the {}.',
        'a photo of the small {}.',
        '{}',
    ],
    'birdsnap': ['a photo of a {}, a type of bird.'],
    'caltech101': [
        'a photo of a {}.',
        'a painting of a {}.',
        'a plastic {}.',
        'a sculpture of a {}.',
        'a sketch of a {}.',
        'a tattoo of a {}.',
        'a toy {}.',
        'a rendition of a {}.',
        'a embroidered {}.',
        'a cartoon {}.',
        'a {} in a video game.',
        'a plushie {}.',
        'a origami {}.',
        'art of a {}.',
        'graffiti of a {}.',
        'a drawing of a {}.',
        'a doodle of a {}.',
        'a photo of the {}.',
        'a painting of the {}.',
        'the plastic {}.',
        'a sculpture of the {}.',
        'a sketch of the {}.',
        'a tattoo of the {}.',
        'the toy {}.',
        'a rendition of the {}.',
        'the embroidered {}.',
        'the cartoon {}.',
        'the {} in a video game.',
        'the plushie {}.',
        'the origami {}.',
        'art of the {}.',
        'graffiti of the {}.',
        'a drawing of the {}.',
        'a doodle of the {}.',
    ],
    'cars196': [
        'a photo of a {}.',
        'a photo of the {}.',
        'a photo of my {}.',
        'i love my {}!',
        'a photo of my dirty {}.',
        'a photo of my clean {}.',
        'a photo of my new {}.',
        'a photo of my old {}.',
    ],
    'cifar10': [
        'a photo of a {}.',
        'a blurry photo of a {}.',
        'a black and white photo of a {}.',
        'a low contrast photo of a {}.',
        'a high contrast photo of a {}.',
        'a bad photo of a {}.',
        'a good photo of a {}.',
        'a photo of a small {}.',
        'a photo of a big {}.',
        'a photo of the {}.',
        'a blurry photo of the {}.',
        'a black and white photo of the {}.',
        'a low contrast photo of the {}.',
        'a high contrast photo of the {}.',
        'a bad photo of the {}.',
        'a good photo of the {}.',
        'a photo of the small {}.',
        'a photo of the big {}.',
    ],
    'cifar100': [
        'a photo of a {}.',
        'a blurry photo of a {}.',
        'a black and white photo of a {}.',
        'a low contrast photo of a {}.',
        'a high contrast photo of a {}.',
        'a bad photo of a {}.',
        'a good photo of a {}.',
        'a photo of a small {}.',
        'a photo of a big {}.',
        'a photo of the {}.',
        'a blurry photo of the {}.',
        'a black and white photo of the {}.',
        'a low contrast photo of the {}.',
        'a high contrast photo of the {}.',
        'a bad photo of the {}.',
        'a good photo of the {}.',
        'a photo of the small {}.',
        'a photo of the big {}.',
    ],
    'clevr_closest_lit_all': [
        '{} objects',
        '{} shapes',
        '{} thing',
        'the nearest shape in this image is {}.',
        'the closest shape in this rendered image is {}.',
        'the closest shape in this image is {}.',
    ],
    'clevr_counts': ['a photo of {} objects.'],
    'clevr_counts_lit_all': [
        '{} objects',
        '{} things',
        'a photo of {} objects.',
        'a picture of {} objects.',
        'there are {} objects.',
        'there are {} objects in the image.',
        'a rendered image of {} objects.',
        'a picture of {} shapes.',
        'there are {} shapes.',
        'there are {} shapes in the image.',
        'a rendered image of {} shapes.',
    ],
    'country211': [
        'a photo i took in {}.',
        'a photo i took while visiting {}.',
        'a photo from my home country of {}.',
        'a photo from my visit to {}.',
        'a photo showing the country of {}.',
    ],
    'dsprites_pos_lit_all': [
        'an object located {}'
    ],
    'dsprites_orient_lit_all': [
        'an object rotated at {}',
        'something rotated at {}',
        '{} rotation',
        'something at a {} rotation',
    ],
    'dtd': [
        'a photo of a {} texture.',
        'a photo of a {} pattern.',
        'a photo of a {} thing.',
        'a photo of a {} object.',
        'a photo of the {} texture.',
        'a photo of the {} pattern.',
        'a photo of the {} thing.',
        'a photo of the {} object.',
    ],
    'dtd_lit_all': ['a {} texture.'],
    'eurosat': [
        'a centered satellite photo of {}.',
        'a centered satellite photo of a {}.',
        'a centered satellite photo of the {}.',
    ],
    'eurosat_lit_all': [
        'a satellite photo of {}.',
        '{} from above.',
        'an aerial view of {}.',
        'an overhead view of {}.',
        'an overhead image of {}.',
        'a satellite image of {}.',
        'photo of {} from the sky.',
    ],
    'facial_emotion_recognition_2013': [
        'a photo of a {} looking face.',
        'a photo of a face showing the emotion: {}.',
        'a photo of a face looking {}.',
        'a face that looks {}.',
        'they look {}.',
        'look at how {} they are.',
    ],
    'fgvc_aircraft': [
        'a photo of a {}, a type of aircraft.',
        'a photo of the {}, a type of aircraft.',
    ],
    # 'food101': ['a photo of {}, a type of food.'],
    'food101': [
        'a photo of {}, a type of food.',
        'a photo of a {}, a type of food.',
    ],
    'gtsrb': [
        'a zoomed in photo of a "{}" traffic sign.',
        'a centered photo of a "{}" traffic sign.',
        'a close up photo of a "{}" traffic sign.',
    ],
    'hateful_memes': ['a {}.'],
    'kitti': ['{}'],
    'kinetics700': [
        'a photo of {}.',
        'a photo of a person {}.',
        'a photo of a person using {}.',
        'a photo of a person doing {}.',
        'a photo of a person during {}.',
        'a photo of a person performing {}.',
        'a photo of a person practicing {}.',
        'a video of {}.',
        'a video of a person {}.',
        'a video of a person using {}.',
        'a video of a person doing {}.',
        'a video of a person during {}.',
        'a video of a person performing {}.',
        'a video of a person practicing {}.',
        'a example of {}.',
        'a example of a person {}.',
        'a example of a person using {}.',
        'a example of a person doing {}.',
        'a example of a person during {}.',
        'a example of a person performing {}.',
        'a example of a person practicing {}.',
        'a demonstration of {}.',
        'a demonstration of a person {}.',
        'a demonstration of a person using {}.',
        'a demonstration of a person doing {}.',
        'a demonstration of a person during {}.',
        'a demonstration of a person performing {}.',
        'a demonstration of a person practicing {}.',
    ],
    'mnist': ['a photo of the number: "{}".'],
    'none': ['{}'],
    'oxford_flowers102': ['a photo of a {}, a type of flower.'],
    'oxford_flowers102_lit_all': ['a {} flower', 'a {} plant'],
    'oxford_iiit_pet': ['a photo of a {}, a type of pet.'],
    'oxford_iiit_pet_lit_all': [
        'a type of pet {}', 'a {} texture', '{}, an animal'
    ],
    'patch_camelyon': ['this is a photo of {}'],
    'patch_camelyon_lit_all': [
        'a histopathology slide showing {}',
        'histopathology image of {}',
        'an example of {}',
        'an example histopathological image showing {}',
        "patient's pathology examination indicates {}",
        'a {} slide',
    ],
    'photo': ['a photo of a {}.'],
    'resisc45': [
        'satellite imagery of {}.',
        'aerial imagery of {}.',
        'satellite photo of {}.',
        'aerial photo of {}.',
        'satellite view of {}.',
        'aerial view of {}.',
        'satellite imagery of a {}.',
        'aerial imagery of a {}.',
        'satellite photo of a {}.',
        'aerial photo of a {}.',
        'satellite view of a {}.',
        'aerial view of a {}.',
        'satellite imagery of the {}.',
        'aerial imagery of the {}.',
        'satellite photo of the {}.',
        'aerial photo of the {}.',
        'satellite view of the {}.',
        'aerial view of the {}.',
    ],
    'resisc45_lit_all': [
        'a satellite photo of {}.',
        '{} from above.',
        'an aerial view of {}.',
        'a satellite image of {}.',
    ],
    'retino_lit_all': [
        'a retinal image with {}',
        'a retina with {}',
        'a fundus image with signs of {}',
    ],
    'smallnorb_azmth_lit_all': [
        'an object rotated at {}',
        'something rotated at {}',
        '{} rotation',
        'something at a {} rotation',
    ],
    'smallnorb_elev_lit_all': [
        'an object rotated at {}',
        'something rotated at {}',
        '{} rotation',
        'something at a {} rotation',
    ],
    'sst2': ['a {} review of a movie.'],
    'stl10': [
        'a photo of a {}.',
        'a photo of the {}.',
    ],
    'sun397': [
        'a photo of a {}.',
        'a photo of the {}.',
    ],
    'svhn_lit_all': [
        'the number {}',
        'a street sign with the number {}',
        'a photo of the number {} written on a sign',
        'an outdoor house number {}',
        'the number {} in the center of the image',
        'an outdoor number {} written on a sign',
        'a centered image of the number {}'
    ],
    'ucf101': [
        'a photo of a person {}.',
        'a video of a person {}.',
        'a example of a person {}.',
        'a demonstration of a person {}.',
        'a photo of the person {}.',
        'a video of the person {}.',
        'a example of the person {}.',
        'a demonstration of the person {}.',
        'a photo of a person using {}.',
        'a video of a person using {}.',
        'a example of a person using {}.',
        'a demonstration of a person using {}.',
        'a photo of the person using {}.',
        'a video of the person using {}.',
        'a example of the person using {}.',
        'a demonstration of the person using {}.',
        'a photo of a person doing {}.',
        'a video of a person doing {}.',
        'a example of a person doing {}.',
        'a demonstration of a person doing {}.',
        'a photo of the person doing {}.',
        'a video of the person doing {}.',
        'a example of the person doing {}.',
        'a demonstration of the person doing {}.',
        'a photo of a person during {}.',
        'a video of a person during {}.',
        'a example of a person during {}.',
        'a demonstration of a person during {}.',
        'a photo of the person during {}.',
        'a video of the person during {}.',
        'a example of the person during {}.',
        'a demonstration of the person during {}.',
        'a photo of a person performing {}.',
        'a video of a person performing {}.',
        'a example of a person performing {}.',
        'a demonstration of a person performing {}.',
        'a photo of the person performing {}.',
        'a video of the person performing {}.',
        'a example of the person performing {}.',
        'a demonstration of the person performing {}.',
        'a photo of a person practicing {}.',
        'a video of a person practicing {}.',
        'a example of a person practicing {}.',
        'a demonstration of a person practicing {}.',
        'a photo of the person practicing {}.',
        'a video of the person practicing {}.',
        'a example of the person practicing {}.',
        'a demonstration of the person practicing {}.',
    ],
    'voc': ['a photo of a {}.'],
}
